create database transaction;
use transaction;
create table property(property_ID int,property_name varchar(30),no_of_floors int,no_of_flats int,sqft_area float);
insert into property values(1,"Shantiniketan",4,80,600.67);
insert into property values(2,"Neel Sidhi",7,120,1000.25);
insert into property values(3,"Adhiraj",3,60,650.67);
insert into property values(4,"Shelter Complex",10,115,1200.67);
insert into property values(5,"Bhoomi Heights",18,200,1500.34);
insert into property values(6,"Goodwill",7,110,800);
select * from property;
insert into property values(7,"Rekhi Residency",15,130,1600);
commit;
select * from property;
update property set no_of_flats=65 where property_name="Adhiraj";
commit;
select * from property;
insert into property values(8,"Ashapuri Residency",5,50,700);
insert into property values(9,"Radhe Residency",7,50,700);
insert into property values(10,"Grow More",12,90,1200.8);
rollback;
select * from property;
delete from property where property_name="Adhiraj";
select * from property;
rollback;
insert into property values(11,"Ambika heights",8,57,1000);
insert into property values(12,"Anmol plaza",7,42,900);
savepoint s1;
insert into property values(13,"Satyam heights",10,100,1100);
select * from property;
rollback to s1;
delete from property where no_of_floors>=10;
savepoint s2;
insert into property values(14,"Nilgiri heights",10,80,1400);
select * from property;

rollback to s2;
select * from property;